### ISSUE TITLE
Feature Request: Add Moto3 and Moto2 races

### ISSUE THREAD

**Issue by ping-spike** [aleuts/MotoiCal#1]
As per title, please add the Moto3 and Moto2 races :)

**Comment by Plus1XP** [comment]
Thanks for the interest in my program. 
I have a big update coming with a lot of options for preferences. 
I'll make sure to add them for you. Expect an update before the start of the season!

**Comment by Siggi0904** [comment]
Hi,
great tool. Good solution to getting the icals.

I would to have to Moto 2 and Moto 3 (and MotoGP) tests, practices and races too.
With this information's we can get all motorbike races in an ical.

Thanks.

**Comment by ping-spike** [comment]
Thanks @Plus1XP  I look forward to the update!

**Comment by Plus1XP** [comment]
@ping-spike @Siggi0904 The program has now been updated to include Moto2/Moto3 (Toggled within settings) and a much needed email feature to send the ical directly to your phone.

**Comment by ping-spike** [comment]
Just wanted to say thanks @Plus1XP 

Works perfectly!!  :clap:
